<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="gioithieu.aspx.cs" Inherits="gioithieu" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .st1 {
            margin:7px 7px 7px 7px;
        }
 p.MsoNormal
	{margin-bottom:.0001pt;
	font-size:12.0pt;
	font-family:"Times New Roman","serif";
	        margin-left: 0in;
            margin-right: 0in;
            margin-top: 0in;
        }
        .auto-style5 {
            color: #FFFF00;
            text-align: center;
            background-color: #000099;
        }
        .auto-style6 {
            font-weight: bold;
        }
        .auto-style7 {
            font-weight: bold;
            color: rgb(0, 0, 0);
            font-size: large;
        }
        .auto-style8 {
            color: rgb(0, 0, 0);
        }
        .auto-style9 {
            font-size: large;
        }
        .auto-style10 {
            font-size: large;
            color: rgb(0, 0, 0);
        }
        .auto-style11 {
            text-align: left;
        }
        .auto-style12 {
            font-weight: bold;
        }
        .auto-style13 {
            font-weight: bold;
            color: rgb(0, 0, 0);
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <asp:Panel ID="Panel1" runat="server" BorderColor="Blue" BorderWidth="2px" 
        Visible="true">  <table style="width:100%; margin-top:20px">
        <tr>
            <td style="font-size: x-large; font-weight: bold" class="auto-style5">LỜI GIỚI THIỆU </td>
        </tr>
        <tr>
            <td style="color: #0066FF;" class="auto-style11">&nbsp;&nbsp;&nbsp;<p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;
margin-left:0in;text-align:justify;text-indent:28.1pt;line-height:150%">
                <span style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; color: rgb(37, 37, 37); font-size: 14px; font-weight: normal;"><b class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Nhà sách</b></span><span class="auto-style8" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><span class="auto-style12">&nbsp;</span></span><span style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; color: rgb(37, 37, 37); font-size: 14px; font-weight: normal;"><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">hay<span class="Apple-converted-space">&nbsp;</span></span><b class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">cửa 
                hàng sách</b><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">hay<span class="Apple-converted-space">&nbsp;</span></span><b class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">hiệu 
                sách</b>,<span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><b class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">tiệm sách</b><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">là 
                một địa điểm nơi thực hiện các giao dịch<span class="Apple-converted-space">&nbsp;</span></span><a class="auto-style13" href="https://vi.wikipedia.org/wiki/Mua" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Mua">mua</a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><a class="auto-style13" href="https://vi.wikipedia.org/wiki/Bán" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Bán">bán</a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><a class="auto-style13" href="https://vi.wikipedia.org/wiki/Sách" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Sách">sách</a><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">. 
                Đây là một điểm bán lẽ của công đoạn phân phối sách trong quá trình xuất bản để những tác phẩm sách đến được với người đọc về bản chất nó cũng là một<span class="Apple-converted-space">&nbsp;</span></span><a class="auto-style13" href="https://vi.wikipedia.org/wiki/Cửa_hàng_bán_lẻ" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Cửa hàng bán lẻ">cửa hàng</a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">chuyên<span class="Apple-converted-space">&nbsp;</span></span><a class="auto-style13" href="https://vi.wikipedia.org/wiki/Kinh_doanh" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Kinh doanh">kinh 
                doanh</a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">về sách. Ngày này Nhà sách hay cửa hàng sách hoặc<span class="Apple-converted-space">&nbsp;</span></span><b class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">siêu 
                thị sách</b><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="auto-style12">&nbsp;</span></span><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">có thể là một phần của một chuỗi, hoặc các hiệu sách độc lập địa phương hoặc trên phạm vi<span class="Apple-converted-space">&nbsp;</span></span><a class="auto-style13" href="https://vi.wikipedia.org/wiki/Toàn_cầu" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Toàn cầu">toàn 
                cầu</a><span class="auto-style13" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">..</span></span></p>
                <p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;
margin-left:0in;text-align:justify;text-indent:28.1pt;line-height:150%">
                    &nbsp;</p>
                <div class="auto-style11">
                    <span class="auto-style10" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></span><span class="auto-style8" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><strong>Mặt hàng kinh doanh chủ yếu cả nhà sách là các loại sách hoặc một số</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Văn_phòng_phẩm" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-size: 14px;" title="Văn phòng phẩm"><strong>văn 
                    phòng phẩm</strong></a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="Apple-converted-space"><strong>&nbsp;</strong></span><strong>nhất định tuy nhiên cửa hàng sách ngày nay thường bán các ấn phẩm bên cạnh các cuốn sách, chẳng hạn như</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Báo" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-size: 14px;" title="Báo"><strong>báo</strong></a><span style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; color: rgb(37, 37, 37); font-size: 14px;">,</span><span style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><span class="auto-style8"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Tạp_chí" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-size: 14px;" title="Tạp chí"><strong>tạp 
                    chí</strong></a><span class="auto-style8" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><span class="Apple-converted-space"><strong>&nbsp;</strong></span><strong>và</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Bản_đồ" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-size: 14px;" title="Bản đồ"><strong>bản 
                    đồ</strong></a><span class="auto-style8" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><strong>... thậm chí là các loại hàng hóa khác. Một số</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Đại_học" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-size: 14px;" title="Đại học"><strong>trường 
                    đại học</strong></a><span class="auto-style8" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><span class="Apple-converted-space"><strong>&nbsp;</strong></span><strong>thường có hiệu sách</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Sinh_viên" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; font-size: 14px;" title="Sinh viên"><strong>sinh 
                    viên</strong></a><span class="auto-style8" style="font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; font-size: 14px;"><span class="Apple-converted-space"><strong>&nbsp;</strong></span><strong>riêng của họ trong khuôn viên nhà trường và thường tập trung vào việc cung cấp</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/wiki/Sách_giáo_khoa" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Sách giáo khoa"><strong>sách 
                    giáo khoa</strong></a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="Apple-converted-space"><strong>&nbsp;</strong></span><strong>và</strong><span class="Apple-converted-space"><strong>&nbsp;</strong></span></span><a class="auto-style8" href="https://vi.wikipedia.org/w/index.php?title=Gi%C3%A1o_tr%C3%ACnh&amp;action=edit&amp;redlink=1" style="text-decoration: none; background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Giáo trình (trang chưa được viết)"><strong>giáo 
                    trình</strong></a><span class="auto-style8" style="font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span class="Apple-converted-space"><strong>&nbsp;</strong></span><strong>cũng như các loại sách hàn lâm, học thuật. Một loại hình phổ biến của các cửa hàng sách là nhà sách chuyên bán sách cũ hoặc thu mua sách cũ ngoài ra loại hình nhà sách trực tuyến ngày nay cũng tương đối phong phú.</strong></span></div>
                <p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;
margin-left:0in;text-align:justify;text-indent:28.1pt;line-height:150%">
                    &nbsp;</p>
                <br /></td>
        </tr>
    </table>
        </asp:Panel>
</asp:Content>

